config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'coworking_spaces#index'
  #get '/login', to: 'sessions#new', as: :login

  resources :users, only: [:new, :create] # 新規登録用のルートを追加
  #resources :sessions, only: [:new, :create, :destroy]

  resources :coworking_spaces do
    resources :reservations, only: [:new, :create]
  end
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  # belongs_to :coworking_space
  with_options presence: true do
    validates :day
    validates :time
    validates :start_time, uniqueness: { message: 'は他のユーザーが予約しています' }
    validates :seat_type_id, numericality: { other_than: 0, message: "can't be blank" }
  end
  validate :date_before_start
  validate :date_three_month_end

  def date_before_start
    return unless day.present?

    errors.add(:day, 'は過去の日付を選択できません。予約画面から正しい日付を選択してください。') if day < Date.current
  end

  def date_three_month_end
    errors.add(:day, 'は3ヶ月以降の日付は選択できません。予約画面から正しい日付を選択してください。') if day && ((Date.current >> 3) < day)
  end

  def self.find_reservation_day(day)
    if day < Date.current
      '過去の日付は選択できません。正しい日付を選択してください。'
    elsif (Date.current >> 3) < day
      '3ヶ月以降の日付は選択できません。正しい日付を選択してください。'
    end
  end

  def self.reservations_after_three_month
    # 今日から3ヶ月先までのデータを取得
    reservations = Reservation.all.where("day >= ?", Date.current).where("day < ?", Date.current >> 3).order(day: :desc)
    # 配列を作成し、データを格納
    # DBアクセスを減らすために必要なデータを配列にデータを突っ込んでます
    reservation_data = []
    reservations.each do |reservation|
      reservations_hash = {}
      reservations_hash.merge!(day: reservation.day.strftime("%Y-%m-%d"), time: reservation.time)
      reservation_data.push(reservations_hash)
    end
    reservation_data
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

  before_action :set_reservation, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :charge] # ログインが必要なアクション名を適宜追加

  def index
    @reservations = Reservation.all.where('day >= ?', Date.current).where('day < ?', Date.current >> 3).order(day: :desc)
  end

  def new
    @reservation = Reservation.new
    @day = params[:day]
    @time = params[:time]
  end

  def show
    @date = params[:day]
  end

  def create
    @reservation = current_user.reservations.build(reservation_params)
    @time = reservation_params[:time]
    if @time.present?
      begin
        parsed_time = Time.parse(@time)
        @reservation.start_time = DateTime.new(@reservation.day.year, @reservation.day.month, @reservation.day.day, parsed_time.hour, parsed_time.min)
      rescue ArgumentError
        flash[:error] = "Invalid time format"
      end
    end

    if @reservation.seat_type_id == 0
      flash[:notice] = '席のタイプを選択してください。'
    else
      if @reservation.save!
        redirect_to coworking_spaces_path
      else
        render :new, status: :unprocessable_entity
      end
    end
  end

  def edit
  end

  def update
    if @reservation.update(reservation_params)
      redirect_to reservation_path(@reservation.id)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @reservation = Reservation.find(params[:id])
    if user_signed_in? && current_user.id == @reservation.user.id
      @reservation.destroy

      respond_to do |format|
        format.html { redirect_to user_path(current_user.id), notice: 'Reservation was successfully deleted.' }
        format.json { render json: { message: "Reservation deleted successfully" }, status: :ok }
        format.js   { render js: "window.location.href = '#{user_path(current_user.id)}'" }
      end
    else
      respond_to do |format|
        format.html { redirect_to user_path(current_user.id), alert: 'Unauthorized action.' }
        format.json { render json: { error: "Unauthorized action" }, status: :unauthorized }
        format.js { render js: "alert('Unauthorized action.'); window.location = '#{user_path(current_user.id)}';" }
      end
    end
  end

    def charge
      token = params[:payjpToken]
      begin
        charge = Payjp::Charge.create(
          amount: 1000, # 金額（ここでは1000円を仮定）
          card: token,
          currency: 'jpy'
        )
        flash[:notice] = "決済が成功しました。"
      rescue Payjp::PayjpError => e
        flash[:alert] = e.message
      end
      redirect_to reservations_path
    end

  private

  def reservation_params
    params.require(:reservation).permit(:day, :time, :user_id, :start_time, :seat_type_id)
  end

  def set_reservation
    @reservation = Reservation.find(params[:id])
  end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
  def times
    ['10:00',
     '10:30',
     '11:00',
     '11:30',
     '13:00',
     '13:30',
     '14:00',
     '15:00',
     '15:30',
     '16:00',
     '16:30',
     '17:00',
     '17:30',
     '18:00 ']
  end
  def check_reservation(reservations, day, time)
    result = false
    reservations_count = reservations.count
    # 取得した予約データにdayとtimeが一致する場合はtrue,一致しない場合はfalseを返します
    if reservations_count > 1
      reservations.each do |reservation|
        result = reservation[:day].eql?(day.strftime("%Y-%m-%d")) && reservation[:time].eql?(time)
        return result if result
      end
    elsif reservations_count == 1
      result = reservations[0][:day].eql?(day.strftime("%Y-%m-%d")) && reservations[0][:time].eql?(time)
      return result if result
    end
    return result
  end
end

app/views/reservations/edit.html.erb
<h2>予約変更ページ<h2>
<%= form_with model: @reservation do |f|%>
  <%= f.label :"予約日" %>
  <%= f.date_field :reservation_date %>
  <%= f.submit "予約を変更する" %>
<% end %>

app/views/reservations/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 text-center">
      <h1>予約画面</h1>
      <p>3ヶ月先まで予約することができます。</p>
    </div>
    <div class="col-12 mt-3">
      <%= week_calendar events: @reservations do |date, reservations| %>
        <%= date.day %>
      <% end %>
    </div>
  </div>
</div>

app/views/reservations/new.html.erb
<!DOCTYPE html>
<html>
 
  <head>
    <meta charset="utf-8">
    <title>COKURU</title>
  </head>

  <body class="reservations-new">

  <div class="container">
  <div class="row">
      <div class="col-12 text-center title">
      <h1>新規予約画面</h1>
      </div>

    <div class="col-12 mt-3 content">
       <% if flash[:notice] %>
        <div class="flash-alert">
          <p><%= flash[:notice] %></p>
        </div>
       <% end %>
       <%= form_with model: @reservation, url: coworking_space_reservations_path, local: true, class: 'form' do |form| %>
        <%= render 'devise/shared/error_messages', resource: form.object %> 
       

      <div class="seat form-group">
        <%= form.label :seat_type, '席のタイプ' %>
        <%= form.text_field :seat_type, class: 'form-control', value: @seat_type %>
          <%= form.select :seat_type_id, [['選択してください',0],['タイプA',1],['タイプB',2],['タイプC',3]], {class:"select-box", id:"seat_type"}%>
      </div>

      <div class="day form-group">
        <%= form.label :day, '日付' %>
        <%= form.date_field :day, class: 'form-control', value: @day %>
      </div>
<div class="time form-group">
  <%= form.label :time, '時間' %>
  <% if @time.present? %>
    <% begin %>
      <% parsed_time = Time.parse(@time) %>
      <%= form.time_field :time, class: 'form-control', value: parsed_time.strftime("%H:%M") %>
    <% rescue ArgumentError %>
      <%= form.time_field :time, class: 'form-control', value: @time %>
    <% end %>
  <% else %>
    <%= form.time_field :time, class: 'form-control' %>
  <% end %>
</div>

       <div class="submit">
        <%= form.submit value: '予約する', class: 'btn btn-primary mx-auto d-block' %>
       </div>
       <% end %>
    <div class="col-12 text-right">
    </div>
  </div>
  </div>
  </div>
</body>
</html>

app/views/reservations/show.html.erb
<h2><%= current_user.name%>さんの予約履歴一覧</h2>

<% @reservation.each do |reservation|%>
  <p>予約日：<%= reservation.reservation_date.strftime('%Y/%m/%d') %></p>
  <% if reservation.reservation_date >= Date.today %>
    <p><%= link_to "編集する", edit_reservation_path(reservation) %></p>
    <p><%= link_to "削除する", reservation_path(reservation), method: :delete %></p>
  <% end %>
<% end %>